### ISSUE TITLE
Compound nodes positioned off grid

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-snap-to-grid#5]
With default options, a compound node's children will all nicely align with the grid and the compound node margins will also be modified to nicely align with the grid. See here:

![before](https://cloud.githubusercontent.com/assets/3874988/16767295/61f17902-4847-11e6-81dd-cebad49448f5.png)

And when you drag child nodes of the compound, they keep nicely aligning with the grid. However, when you drag the compound, sometimes, the compound gets positioned off the grid (resulting in children not properly aligning with the grid). See below:

![after](https://cloud.githubusercontent.com/assets/3874988/16767347/a154e6f6-4847-11e6-98db-da77a93face7.png)

**Comment by mrsfy** [comment]
It seems more stable now. May you confirm?

**Comment by ugurdogrusoz** [comment]
Looks fine!
